# Generated by Django 3.0.5 on 2020-05-18 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERENTITIES',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.Entity')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.EntityTags')),
            ],
        ),
        migrations.AddField(
            model_name='entitytags',
            name='relentity',
            field=models.ManyToManyField(related_name='tags_list', through='api_basic.Rel', to='api_basic.Entity'),
        ),
        migrations.AddField(
            model_name='entitytags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
