# Generated by Django 3.0.5 on 2020-04-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20200429_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['-created_at']},
        ),
    ]
